package io.pleo.antaeus.core.exceptions

class NetworkException : RuntimeException("A network error happened please try again.")
